{"name": "User logs in with invalid credentials -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to redirect to login page or incorrect behavior detected: Test failed. Wrong user but login successfully: Message: \nStacktrace:\n\tGetHandleVerifier [0x00007FF78A7D38A5+3004357]\n\t(No symbol) [0x00007FF78A469970]\n\t(No symbol) [0x00007FF78A31582A]\n\t(No symbol) [0x00007FF78A365B8E]\n\t(No symbol) [0x00007FF78A365E7C]\n\t(No symbol) [0x00007FF78A3AEC27]\n\t(No symbol) [0x00007FF78A38BC1F]\n\t(No symbol) [0x00007FF78A3ABA4C]\n\t(No symbol) [0x00007FF78A38B983]\n\t(No symbol) [0x00007FF78A357628]\n\t(No symbol) [0x00007FF78A358791]\n\tGetHandleVerifier [0x00007FF78A7FA00D+3161901]\n\tGetHandleVerifier [0x00007FF78A84E060+3506048]\n\tGetHandleVerifier [0x00007FF78A84400D+3465005]\n\tGetHandleVerifier [0x00007FF78A5C0EEB+830987]\n\t(No symbol) [0x00007FF78A47467F]\n\t(No symbol) [0x00007FF78A4709D4]\n\t(No symbol) [0x00007FF78A470B6D]\n\t(No symbol) [0x00007FF78A460149]\n\tBaseThreadInitThunk [0x00007FF8DFCB259D+29]\n\tRtlUserThreadStart [0x00007FF8E112AF38+40]\n\n", "trace": "  File \"D:\\claire\\04_練習\\workspace\\VM\\env\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"D:\\claire\\04_練習\\workspace\\VM\\env\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\login_steps.py\", line 86, in step_impl\n    raise AssertionError(f\"Failed to redirect to login page or incorrect behavior detected: {inner_exception}\")\n"}, "steps": [{"name": "Given the user is on the login page", "status": "passed", "start": 1731652481297, "stop": 1731652481724}, {"name": "When the user enters Username as \"1002327011\" and Password as \"admin\"", "status": "passed", "start": 1731652481724, "stop": 1731652482854}, {"name": "Then the user should be redirected to the login page", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to redirect to login page or incorrect behavior detected: Test failed. Wrong user but login successfully: Message: \nStacktrace:\n\tGetHandleVerifier [0x00007FF78A7D38A5+3004357]\n\t(No symbol) [0x00007FF78A469970]\n\t(No symbol) [0x00007FF78A31582A]\n\t(No symbol) [0x00007FF78A365B8E]\n\t(No symbol) [0x00007FF78A365E7C]\n\t(No symbol) [0x00007FF78A3AEC27]\n\t(No symbol) [0x00007FF78A38BC1F]\n\t(No symbol) [0x00007FF78A3ABA4C]\n\t(No symbol) [0x00007FF78A38B983]\n\t(No symbol) [0x00007FF78A357628]\n\t(No symbol) [0x00007FF78A358791]\n\tGetHandleVerifier [0x00007FF78A7FA00D+3161901]\n\tGetHandleVerifier [0x00007FF78A84E060+3506048]\n\tGetHandleVerifier [0x00007FF78A84400D+3465005]\n\tGetHandleVerifier [0x00007FF78A5C0EEB+830987]\n\t(No symbol) [0x00007FF78A47467F]\n\t(No symbol) [0x00007FF78A4709D4]\n\t(No symbol) [0x00007FF78A470B6D]\n\t(No symbol) [0x00007FF78A460149]\n\tBaseThreadInitThunk [0x00007FF8DFCB259D+29]\n\tRtlUserThreadStart [0x00007FF8E112AF38+40]\n\n", "trace": "  File \"D:\\claire\\04_練習\\workspace\\VM\\env\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"D:\\claire\\04_練習\\workspace\\VM\\env\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\login_steps.py\", line 86, in step_impl\n    raise AssertionError(f\"Failed to redirect to login page or incorrect behavior detected: {inner_exception}\")\n"}, "start": 1731652482855, "stop": 1731652493295}], "parameters": [{"name": "username", "value": "1002327011"}, {"name": "password", "value": "admin"}], "start": 1731652481296, "stop": 1731652493296, "uuid": "b3a4513d-f76b-40fe-86b5-37d07edd7d6a", "historyId": "020df18e3ec989586d9c4c0a799c204f", "fullName": "User Login: User logs in with invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}